apiVersion: apps/v1
kind: Deployment
metadata:
  name: nordcloud-notejam
  labels:
    app: nordcloud-notejam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nordcloud-notejam
  template:
    metadata:
      labels:
        app: nordcloud-notejam
    spec:
      containers:
      - name: nordcloud-notejam
        image: $ECR_REGISTRY/$ECR_REPOSITORY:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
            memory: 
          limits:
            cpu: 500m
            memory: 