apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nordcloud-notejam
  labels:
    app: nordcloud-notejam
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nordcloud-notejam
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
